# Generated by Django 4.1.2 on 2022-10-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=20, verbose_name='نام مهارت خود را وارد کنید')),
                ('skill_percentage', models.IntegerField(default=0, verbose_name='درصد مهارت خود را وارد کنید')),
            ],
        ),
    ]
