# Generated by Django 4.1.2 on 2022-10-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=20, verbose_name='نام زبانی که میتوانید صحبت کنید را وارد کنید')),
                ('language_percentage', models.IntegerField(default=0, verbose_name='درصد تسلط خود بر روی زبان مورد نظر را وارد کنید')),
            ],
        ),
    ]
