# Generated by Django 4.1.2 on 2022-10-21 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=20, verbose_name='نام و نام خانوادگی')),
                ('img', models.ImageField(upload_to='picture', verbose_name='آواتار خود را انتخاب کنید')),
                ('berth_day', models.DateField(verbose_name='تاریخ تولد خود را انتخاب کنید')),
                ('website', models.URLField(verbose_name='وب سایت خود را وارد کنید ')),
                ('phone', models.CharField(max_length=15, verbose_name='شماره تماس خود را وارد کنید')),
                ('city', models.CharField(max_length=15, verbose_name='محل زندگی خود را وارد کنید')),
                ('degree', models.CharField(choices=[('Junior', 'Junior'), ('Middle_Level', 'Middle Level'), ('Senior', 'Senior')], max_length=20, verbose_name='سطح مهارت خود را وارد کنید')),
                ('email', models.EmailField(max_length=30, verbose_name='ایمیل خود را وارد کنید')),
                ('freelance', models.BooleanField(default=False, verbose_name='آیا میتوانید به صورت آزادانه کار کنید ')),
                ('description', models.TextField(max_length=500, verbose_name='توضیحات در مورد خود ')),
                ('twitter', models.CharField(max_length=50, verbose_name='آدرس حساب کاربری توییتر خود را وارد کنید')),
                ('instagram', models.CharField(max_length=50, verbose_name='آدرس حساب کاربری اینستاگرام خود را وارد کنید')),
                ('facebook', models.CharField(max_length=50, verbose_name='آدرس حساب کاربری فیس بوک خود را وارد کنید')),
                ('github', models.CharField(max_length=50, verbose_name='آدرس حساب کاربری گیت هاب خود را وارد کنید')),
            ],
        ),
    ]
