# Generated by Django 4.1.2 on 2022-10-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Information', '0002_information_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social_Media_followers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media_name', models.CharField(max_length=20, verbose_name='نام پلتفرم مورد نظر را وارد کنید')),
                ('Social_Media_follower_count', models.IntegerField(default=0, verbose_name='تعداد فالور خود را وارد کنید')),
            ],
        ),
    ]
