# Generated by Django 4.1.2 on 2022-12-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Information', '0003_social_media_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='location',
            field=models.CharField(default=True, max_length=200, verbose_name='آدرس محل زندگی خود را وارد کنید'),
        ),
    ]
