# Generated by Django 4.1.2 on 2022-12-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Information', '0004_information_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='visit_count',
            field=models.IntegerField(default=0, verbose_name='تعداد بازدید'),
        ),
    ]
