# Generated by Django 4.1.2 on 2022-12-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('job', models.CharField(max_length=50, verbose_name='شغل')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل خود را وارد کنید ')),
                ('subject', models.CharField(max_length=150, verbose_name='عنوان')),
                ('comment', models.TextField(verbose_name='سخن خود')),
                ('show_massage', models.BooleanField(default=False, verbose_name='آیا میخواهید پیام شما برای دیگران نمایش داده شود ؟')),
            ],
        ),
    ]
